config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :users
  post 'users/search' => 'users#search'
  resources :books
  post 'books/search' => 'books#search'
  #get 'books/authors' => 'books#authors'
  get 'authors', to: 'books#authors'
  resources :opinions
  get 'login', to: 'sessions#new'
  get 'api/books/json', to: 'books#getJSON'
  get 'api/users/json', to: 'users#getJSON'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/book.rb
require 'net/http'
class Book < ApplicationRecord
    has_many    :opinions
    validates :title,   presence: {message: "Musisz podać tytuł"}
    validates :author,  presence: {message: "Musisz podać autora"}
    validates :genre,   presence: {message: "Musisz podać kategorię"}


    def position
      books = Book.all
      i=1
      books.each do |book|
        if book.id == self.id
          return i
        end
        i+=1
      end
    end
end

app/controllers/books_controller.rb
require 'net/http'
class BooksController < ApplicationController
   before_action :require_admin, only: [:destroy, :edit, :update, :new, :create]
   before_action :set_book, only: [:show, :update, :edit, :destroy]
   before_action :check_book, only: [:create, :update]
   def index
       @books = Book.paginate(page: params[:page], per_page: 10)
   end
   def new
       @book = Book.new
   end
   def create
        if @book.save
          flash[:success] = "Książka została prawidłowo dodana"
          redirect_to books_path
        else
          render 'new'
        end
   end
   def show
       @opinion = Opinion.new
       if !@book.opinions.empty?
           @average = 0
           @book.opinions.each { |o| @average += o.rate }
           @average = (@average.to_f / @book.opinions.size).to_f.round(2)
       end
       @lastpage = (@book.position / 10.to_f).ceil
       cookies[:bookid] = @book.id
       if logged_in?
         url = URI("http://bookrater-env.fip3fudrqp.eu-west-1.elasticbeanstalk.com/?query={ predictedRatings(users: #{current_user.id}, books: #{@book.id}) }")
         response = Net::HTTP.get_response(url)
           begin
             data = JSON.parse(response.body)
             if data['errors']
               @rate = "Wystąpił błąd"
             else
               @rate = data['data']['predictedRatings'][0]
               @rate = "#{@rate.round(3)}/5"
             end
           rescue
             @rate = "Błąd serwera"
           ensure

           end
     end
   end
   def edit
   end
   def update
       if @book.update(book_param)
          flash[:success] = "Pozycja została edytowana"
          redirect_to books_path
       else
          render 'edit'
       end
   end
   def destroy
       @book.opinions.destroy_all
       if @book.destroy
         flash[:danger] = "Pozycja została usunięta"
         redirect_to books_path
       else
          redirect_to books_path
       end
   end
   def search
      if !params[:orders]
          @books = Book.where('LOWER(title) LIKE :search OR LOWER(author) LIKE :search OR LOWER(genre) LIKE :search', search: "%#{params[:search].strip.downcase}%")
      else
          if params[:sort]== "ASC" || params[:sort] == "DESC"
            @books = Book.where('LOWER(title) LIKE :search OR LOWER(author) LIKE :search OR LOWER(genre) LIKE :search', search: "%#{params[:search].strip.downcase}%").order("#{params[:orders]} #{params[:sort]}")
          else
              flash[:danger] = "Zrobiłeś coś źle"
              redirect_to books_path
          end
      end
   end
   def authors
      @books = Book.all
      @authors = Array.new
      @books.each do |book|
         if @authors.include? book.author

         else
             @authors << book.author
         end
      end
      @authors.sort!
   end
   def getJSON
      @books = Book.all
      render json: @books.to_json(:include => :opinions)
   end
   private
   def set_book
      begin
         @book = Book.find(params[:id])
      rescue
         flash[:danger] = "Coś sknociłeś"
         redirect_to root_path
      ensure

      end
   end
   def book_param
      params.require(:book).permit(:title, :author, :genre)
   end
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Tylko admin może zrobić coś takiego"
            redirect_to root_path
        end
    end
    def check_book
        @book = Book.new(book_param)
        if Book.where(["title = ? and author = ?", "#{@book.title}", "#{@book.author}"]).exists?
                flash[:info] = "Taka książka już istnieje"
                redirect_to(request.env['HTTP_REFERER'])
        end
    end
end

app/views/books/_form.html.erb
<h4 >Dodaj opinię</h4>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(Opinion.new, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Opis</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, class: "form-control", rows: 5, maxlength: 1000, placeholder: "Zrecenzuj książkę", autofocus: true, id: "description" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Ocena</label>
                </div>
                <div class="col-sm-8">
                    <%= f.select :rate, options_for_select([1,2,3,4,5], 1), class: 'form-control', id: "rate" %>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.button "Dodaj opinie", class: 'btn btn-primary btn-lg', id: "submit" %>
                </div>
            </div>
            <% end %>

    </div>
</div>

app/views/books/authors.html.erb
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<p></p>

<div class="container">

	<div class="row">
		<section class="content">
		
			<div class="col-md-8 col-md-offset-2">
			
			 <% @authors.each do |au| %>

				<div class="panel panel-default">
				
					<div class="panel-body">
					
						<div class="table-container">
						

							<table class="table table-filter">
							
								<tbody>
								
								
									<tr >
											<div class="media">
												<a href="#" class="pull-left">
													<img src="https://png.icons8.com/ios/2x/book.png" class="media-photo">
												</a>
												<div class="media-body">
													<h4 class="title">
														<%= link_to "Książki autora: #{au}", books_search_path(search: "#{au}") , method: :post %>
													</h4>
													   <% @books.where(author: "#{au}").each do |b| %>
													   <p class="summary">

    					<%= link_to "#{b.title}", book_path(b.id) %>
												   	</p>
										<% end %>
												</div>
										
											</div>
											
										</td>
										
									
									</tr>
									
								
									
								</tbody>
								
							
							</table>
								
						</div>
						
					</div>
					
				</div>
				
				<% end %>
				
			</div>
		</section>
		
	</div>
</div>



<!--

<% @authors.each do |au| %>
<div>
    <h2><%= link_to "Książki autora: #{au}", books_search_path(search: "#{au}") , method: :post %></h2>
    <% @books.where(author: "#{au}").each do |b| %>
    <p><%= link_to "#{b.title}", book_path(b.id) %></p>
    <% end %>
</div>
<% end %>

-->

app/views/books/edit.html.erb
<%= render 'layouts/errors', obj: @book %>
<h1 align="center">Edytuj książkę<br> <%= @book.title %></h1>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Tytuł</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Tytuł", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Autor</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :author, class: "form-control", placeholder: "Autor", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Gatunek</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :genre, class: "form-control", placeholder: "Gatunek", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit "Edytuj", class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
            <% end %>
    </div>
</div>

app/views/books/index.html.erb
<div align='center'>
    <%= will_paginate %>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Tytuł</th>
        <% if logged_in? && current_user.admin? %>
        <th>Edytuj (admin)</th>
        <th>Usuń (admin)</th>
        <% end %>
        <th>Autor</th>
        <th>Kategoria</th>
      </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr id="book-<%=book.id%>">
            <td><%= link_to "#{book.title}", book_path(book), class: "btn btn-xl btn-default" %>
                    <% if logged_in? && current_user.admin? %>
                    <td><%= link_to 'Edytuj', edit_book_path(book.id), class: "btn btn-xs btn-primary" %></td>
                    <td><%= link_to 'Usuń', book_path(book.id), method: :delete, class: "btn btn-xs btn-danger" %></td>
                    <% end %>
            </td>
            <td><%= book.author %></td>
            <td><%= book.genre %></td>
        </tr>
        <% end %>
    </tbody>
</table>
    <%= will_paginate %>
</div>

app/views/books/new.html.erb
<%= render 'layouts/errors', obj: @book %>
<h1 align="center">Dodaj książkę</h1>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Tytuł</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Tytuł", autofocus: true, id: "title" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Autor</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :author, class: "form-control", placeholder: "Autor", autofocus: true, id: "author" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Gatunek</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :genre, class: "form-control", placeholder: "Gatunek", autofocus: true, id: "genre" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.button "Dodaj", class: 'btn btn-primary btn-lg', id: "submit" %>
                </div>
            </div>
            <% end %>
    </div>
</div>

app/views/books/search.html.erb
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<p></p>

<div id="divparams" style="display: none;">
    <%= "#{params[:orders]},#{params[:sort]}" %>
</div>
<% if !@books.empty? %>

<div class="container">

	<div class="row">
		<section class="content">
		
			<div class="col-md-8 col-md-offset-2">
			
			 <% @books.each do |b| %>

				<div class="panel panel-default">
				
					<div class="panel-body">
					
						<div class="table-container">
						

							<table class="table table-filter">
							
								<tbody>
								
								
									<tr >
											<div class="media">
												<a href="#" class="pull-left">
													<img src="https://png.icons8.com/ios/2x/book.png" class="media-photo">
												</a>
												<div class="media-body">
													<h4 class="title">
														<%= link_to "#{b.title}", book_path(b.id) %>      
													</h4>
													   
													   <p class="summary">
<div><%= "#{b.author}" %></div> <div><%= "#{b.genre}" %></div>
    					
        <% if logged_in? && current_user.admin? %>
            <%= link_to 'Usuń', book_path(b.id), method: :delete, class: "btn btn-xs btn-danger" %>
        <% end %>
												   	</p>
										
												</div>
										
											</div>
											
										</td>
										
									
									</tr>
									
								
									
								</tbody>
								
							
							</table>
								
						</div>
						
					</div>
					
				</div>
				
				<% end %>
				
			</div>
		</section>
		
	</div>
</div>













<!--
    <% @books.each do |b| %>
    <p>
        <%= link_to "#{b.title}", book_path(b.id) %> 
        <%= "#{b.author} #{b.genre}" %>
        <% if logged_in? && current_user.admin? %>
            <%= link_to 'Usuń', book_path(b.id), method: :delete, class: "btn btn-xs btn-danger" %>
        <% end %>
    </p>
    <% end %>
    
    -->
    
<% else %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">Brak obiektów dla frazy <%= params[:search] %></h2>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/books/show.html.erb
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<p></p>

<div class="container">
	<div class="row">

		<section class="content">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">

						<div class="table-container">
							<table class="table table-filter">
								<tbody>


									<tr >
										<td>
											<div class="media">
												<a href="#" class="pull-left">
													<img src="https://png.icons8.com/ios/2x/book.png" class="media-photo">
												</a>
												<div class="media-body">
													<h4 class="title">
														<div><%= @book.title %></div>
													</h4>
													<p class="summary">
													<div><%= @book.author %></div>
<div><%= @book.genre %></div>
<div><%= "Średnia #{@average}" %></div>
<div><%= "Przewidywana: #{@rate}" %></div>


													</p>
												</div>
											</div>
										</td>
									</tr>
									<% if current_user %>
									<tr >
										<td>
											<div class="media">
												<a href="#" class="pull-left">
													<img src="https://cdn.ning.com/wp-content/themes/ningblog/assets/img/ui/blog/icons/review-icon.png" class="media-photo">
												</a>
												<div class="media-body">

													<p class="summary">


<%= render partial: "form", locals: {opinion: @opinion} %>

													</p>
												</div>
											</div>
										</td>
									</tr>
									<% end %>
									<% @book.opinions.each do |opinion| %>
									<tr >
										<td>
											<div class="media">
												<a href="#" class="pull-left">
													<img src="https://cdn.ning.com/wp-content/themes/ningblog/assets/img/ui/blog/icons/review-icon.png" class="media-photo">
												</a>
												<div class="media-body">

													<p class="summary">

													 <% if opinion.description %>
        <%= "#{opinion.user.username} ocenił #{opinion.rate}/5: #{opinion.description}" %>
        <% if  current_user && (current_user.admin? || current_user.id == opinion.user_id) %>
            <%= link_to 'Usuń', opinion_path(opinion.id), method: :delete, class: "btn btn-xs btn-danger" %>
        <% end %>
    <% end %>

													</p>
												</div>
											</div>
										</td>
									</tr>

									<% end %>
<div><%= link_to "Powrót", books_path(page: @lastpage), class: "btn btn-xl btn-info", id: 'back' %></div>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>

	</div>
</div>

<!--

<div><%= @book.title %></div>
<div><%= @book.author %></div>
<div><%= @book.genre %></div>
<div><%= "Średnia #{@average}" %></div>
<%= render partial: "form", locals: {opinion: @opinion} %>


<% @book.opinions.each do |opinion| %>
<div class='row'>
    <% if opinion.description %>
        <%= "#{opinion.user.username} ocenił #{opinion.rate}/10: #{opinion.description}" %>
        <% if  current_user && (current_user.admin? || current_user.id == opinion.user_id) %>
            <%= link_to 'Usuń', opinion_path(opinion.id), method: :delete, class: "btn btn-xs btn-danger" %>
        <% end %>
    <% end %>
</div>
<% end %>


-->