config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :users
  post 'users/search' => 'users#search'
  resources :books
  post 'books/search' => 'books#search'
  #get 'books/authors' => 'books#authors'
  get 'authors', to: 'books#authors'
  resources :opinions
  get 'login', to: 'sessions#new'
  get 'api/books/json', to: 'books#getJSON'
  get 'api/users/json', to: 'users#getJSON'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">


</div>
    <small>Wydział Zastosowań Informatyki i Informatyki</br></small>
    <small><a href="https://github.com/danieln96/BookWeb_SIAG" target="_blank">github</a></small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">×</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<head>
<script type='text/javascript'
  src='http://code.jquery.com/jquery-2.0.2.js'></script>
<script type='text/javascript'
  src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
<script type='text/javascript'>//<![CDATA[ 
$(window).load(function(){<!--  w w w  .  java 2  s  . c  o  m-->
$(function() {
    var navbarOffset = $(".navbar").height() + 10;
    var shiftWindow = function() { scrollBy(0, -navbarOffset); };
    window.addEventListener("hashchange", shiftWindow);
    if (window.location.hash) shiftWindow();
});
$("a[href^='#']").on('click', function(e) {
   e.preventDefault();
   var hash = this.hash;
   $('html, body').animate({
       scrollTop: $(this.hash).offset().top - 60
     }, 300, function(){
         window.location.hash = hash;
     });
});
});//]]>  
</script>

</head>

<div style="background-color:#111111;">
    <nav class="navbar navbar-inverse" style="margin:0;border:1;background-color:#111111;">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" style="background-color:#111111;">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">BookWeb</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse" style="background-color:#111111;">
            <ul class="nav navbar-nav" style="background-color:#111111;">
                <li class="active"><%= link_to 'Strona główna', root_path, id: 'mainsite' %></li>
                <li>  <%= link_to "Lista książek", books_path, id: 'books' %></li>
                <li>  <%= link_to 'Użytkownicy', users_path, id: 'users' %></li>
                <li>  <%= link_to "Autorzy", authors_path, id: 'authors' %></li>
                <% if logged_in? && current_user.admin? %>
  <li><%= link_to 'Dodaj książkę', new_book_path, id: 'addbook' %></li>
  <% end %>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
            <li><a href="#SectionID">Szukaj książki</a></li>
                 <% if logged_in? %>
  <li><%= link_to "Wyloguj", logout_path, method: :delete, id: 'logout' %></li>
 <li> <%= link_to 'Twój profil', user_path(current_user), id: 'profile' %></li>
  <% else %>
 <li> <%= link_to "Utwórz konto", new_user_path,  id: 'register' %></li>
 <li> <%= link_to "Logowanie", login_path, id: 'login' %></li>
  <% end %>
            </ul>
        </div>
    </nav>
</div>


<!--/
<div>
  <% if logged_in? %>
  <%= link_to "Wyloguj", logout_path, method: :delete, class: "btn btn-xs btn-danger", id: 'logout' %>
  <%= link_to 'Twój profil', user_path(current_user), class: "btn btn-xs btn-success", id: 'profile' %>
  <% else %>
  <%= link_to "Utwórz konto", new_user_path, class: "btn btn-xs btn-success", id: 'register' %>
  <%= link_to "Logowanie", login_path, class: "btn btn-xs btn-success", id: 'login' %>
  <% end %>
  <%= link_to 'Strona główna', root_path, class: "btn btn-xs btn-success", id: 'mainsite' %>
  <%= link_to "Lista książek", books_path, class: "btn btn-xs btn-success", id: 'books' %>
  <%= link_to 'Użytkownicy', users_path, class: "btn btn-xs btn-success", id: 'users' %>
  <%= link_to "Autorzy", authors_path, class: "btn btn-xs btn-success", id: 'authors' %>
  <% if logged_in? && current_user.admin? %>
  <%= link_to 'Dodaj książkę', new_book_path, class: "btn btn-xs btn-success", id: 'addbook' %>
  <% end %>
</div>




<div class='col-sm-3'>
  <%= form_tag(books_search_path, method: "post") do %>
  <%= label(:search, "Szukaj książki") %>
  <%= text_field_tag :search, params[:search], placeholder: "Tytuł/Autor/Gatunek", class: 'form-control' %>
  <%= label(:orders, "Sortuj po") %>
  <%= select_tag "orders", options_for_select([["Tytuł","title"], ["Autor","author"], ["Gatunek", "genre"]], "Książka"), class: 'form-control' %>
  <%= select_tag 'sort', options_for_select([["Rosnąco", "ASC"],["Malejąco", "DESC"]]), class: 'form-control' %>
  <%= submit_tag("Szukaj") %>
  <% end %>
</div>
-->

app/views/layouts/_search.html.erb
<div class="row" id="SectionID" style="padding:0px; width:100%;">
<div style="width:500px; margin:0 auto; padding:0px;">
<div style="text-align: center; margin:90px; padding:0px;/">
  <%= form_tag(books_search_path, method: "post") do %>
  <%= label(:search, "Szukaj książki") %>
  <%= text_field_tag :search, params[:search], placeholder: "Tytuł/Autor/Gatunek", class: 'form-control' %>
  <%= label(:orders, "Sortuj po") %>
  <%= select_tag "orders", options_for_select([["Tytuł","title"], ["Autor","author"], ["Gatunek", "genre"]], "Książka"), class: 'form-control' %>
  <%= select_tag 'sort', options_for_select([["Rosnąco", "ASC"],["Malejąco", "DESC"]]), class: 'form-control' %>
  <%= submit_tag("Szukaj" ) %>
  <% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/navbar' %>
<p></p>
<div>
  <%= render 'layouts/messages' %>
  <%= yield %>
  <%= render 'layouts/search' %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>